#!/bin/bash

Tarball="0.5.tar.gz"
curl -sL https://github.com/goody80/ccci/archive/$Tarball -o ./ccci.tgz && tar zxf ccci.tgz && mv ccci-* ccci && rm -f ccci.tgz
echo " ! You just type like this command -> ./quickstart.sh in the 'ccci' directory"
